### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by ankit** [codysherman/Scroll-to-Top-Button-Extension#1]
It'll be awesome if you can add a customizable keyboard shortcut. Also, make sure it allows alt, ctrl, etc.

That's the probably the only left out feature. I don't know what's the shortcut to go to top on Windows. On Mac I know it's Cmd+up arrow. Nice UI, btw.

**Comment by codysherman** [comment]
It is being worked on, expected for next release (SOON!)

**Comment by codysherman** [comment]
It is finished and released! :)
